### ISSUE TITLE
How will testers submit feedback?

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#176]
Where shall they submit feedback and bug reports to? How will we guide them as to how to fill out the feedback and bug reports in a useful way?

In my opinion, there should at the very least be a button that leads to an immediate way to give feedback.

**Comment by lianilychee** [comment]
Can I clarify a few things?

> feedback

What kind of feedback do you mean?  UI / UX / bugs?  Or more product-oriented ones, like "do you see this changing how you advise clients?  Would you use it?  Does this actually fit your needs?"

> testers

There are two kinds of testers:  (1) ones that CfB will be demoing to, face-to-face, and (2) those that will encounter the tool through referral (they get the link somehow and aren't with a CfB member when they click through.)

I'm not worried about Group 1 because we'll be with them.  We are going to be speaking w/ testers to evaluate product need with each demo, so we can roll UI stuff in as well, and physically write things down.

Group 2 - how large do you think this group will be?  (cc: @anhase)  My hunch is that it'll be <20 people, and the feedback - both UI/UX and product - will be rather similar across both groups.  So why inundate ourselves with duplicate material?  The reality is the product team does not have enough people power to handle large volumes of information.

> at the very least be a button

Like a text box where people just write what they encountered, and then hit 'submit'?  Or a complete instrumentation of every possible interaction that, when clicked, creates a flag for us?

I think the latter would be awesome but rather overkill.  I can see the former executed as a Google Form link in the disclaimer (would have to tweak disclaimer language accordingly).  For scaffolding to get something meaningful, I can't think of something short and sweet off the top of my head -- at which point I echo my sentiment about duplicate data being more of a burden than a boon.

**Comment by knod** [comment]
> feedback

I mean the smaller stuff - bugs, was an input unclear - small picture stuff. Bigger picture stuff is probably a face to face conversation. I'm not sure our users will differentiate, though.

> at the very least be a button

I'm talking about one button - either a way to submit feedback right there, or a link to a way to submit feedback, like to a google form. It could go on the 'About' page (see Nick's description in #177).

I think it's good to have one-on-one conversations, but it's also good to have feedback about immediate impressions, especially when someone isn't there to observe the interaction. Maybe that won't ever be a situation, though.

**Comment by anhase** [comment]
We should fold feedback and contact onto the same line on the "About" page, using language like, "Find a bug? Want to learn more? Contact us at: xyz@codeforboston.org."

**Comment by knod** [comment]
Being dealt with through 'About' page content, #171
