### ISSUE TITLE
Money amount entry should not have increment controls

### ISSUE THREAD

**Issue by sashamaryl** [codeforboston/cliff-effects#190]
The money-entry fields have increment controls in them which increment by cents. This is not a realistic way to enter money amounts.

I recommend that the increment buttons be removed and the entry should just be by keyboard, at least for the MVP.

**Comment by ManickYoj** [comment]
Yes. The result of the team discussion on 11/14/17 was that we should remove the increment buttons.
![image](https://user-images.githubusercontent.com/2252820/32815221-e0311708-c980-11e7-8b63-f1b08737af0b.png)

**Comment by knod** [comment]
@scapp281: The fix from #209 allows text to be typed into the number input. Only numbers should be allowed in there, which is why the `type` attribute was set to 'number'. We need to find another way to do this.

**Comment by knod** [comment]
@lianilychee and @anhase: Do we want all number input fields to have their arrows removed, or just the ones involving money?

**Comment by lianilychee** [comment]
The only number input fields that aren't $-involved are the questions in household, right?

I think because those fields are relatively few in quantity (because we've only a couple of benefits + you've done such a great job at conditional question display!), we may as well be consistent and remove the increment arrows for all.

**Comment by knod** [comment]
Fixed with #213
