### ISSUE TITLE
Re-center form elements since last change

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#192]
Unless we want them left-aligned, which is fine too. This is regarding things like the toggles for the 'Current Benefits' form section, etc.

#191 changed something so that they're all left-aligned now. Obviously something was a bit fragile.

**Comment by ManickYoj** [comment]
I changed it. There was a grid global center allign on the `VisitPage` that I removed.

I considered re-center-aligning the form elements but preferred the UI with the significant note that along with it, I aligned the content of the visit page within a centered container element to match the content of the other pages, whereas it had previously spread to the screen edges.

I'm reclassifying this from bug to discussion to note that this may be a difference of opinion rather than an unintended bug.

**Comment by knod** [comment]
It does seem design sensibilities have changed and centering is no longer desired, so this is a non-issue! Huzzah!

**Comment by sashamaryl** [comment]
I think that we should narrow the center column (by setting a max width I guess?). We should indeed have consistency, but it shouldn't be that far to the left. 

![left-aligned-to-far](https://user-images.githubusercontent.com/30247522/32844311-10ceafb4-c9f0-11e7-832c-a815486e6df0.png)

Mostly it's affecting that first line of the body: after reading the title, you have to go so far to the left to find it. I would argue that the rest of the questions are affected similarly, though it's less obvious to look at. It still takes a little more effort to scan even though the actual column is narrow at that point.

Here is an article about column-width and readability that explains it better than I can. It's not about questionnaires in particular, but the principles apply: https://baymard.com/blog/line-length-readability. 

I think left alignment with a narrower container would do us good. It would give us the best-of-both left-aligned and centered. 

The big text blocks feel okay, but still feel shifted to the left from the title. The centered title should definitely be centered over the text block, whatever we end up doing. 

I notice in reviewing this that the right margin of the text is aligned with the inside of the 'next' button, and the left side of the text is aligned with the outside of the 'previous' button. I will enter this as a feature/bug because we definitely should have the content equal over the buttons, and I would definitely move it to the inside. I wonder if that nudge will put our left margin in the correct spot? 

Further thought: If it isn't prohibitively time-consuming, I think that the monthly-yearly-weekly sections should have their own consistent alignment indented from the primary left edge. It would end up looking something like a paragraph-length quote in a book. It would make the ones within text more consistent with the ones which are on their own (or at least seem that way).

**Comment by knod** [comment]
@sashamaryl: Just something to keep in mind here - if you pick some form inputs, the expenses page can have a lot of text, so we don't want element locations jumping when some form value has been changed. (I'll save any further thoughts till I've read your comment more deeply.)
