### ISSUE TITLE
Make script/test to check whether localization files are valid or how much they are missing

### ISSUE THREAD

**Issue by ethanbb** [codeforboston/cliff-effects#527]
Come up with some easy way to automatically check the validity and/or coverage of localization files, relative to `en.js`.

Google localization docs: https://drive.google.com/drive/folders/1QDCwxmTWZ8-9nLUg_b0M47UYaHXFR3n0

**Comment by jlangevin** [comment]
The pull request I just submitted affected the localization files.  Assuming that PR is accepted, I'd love to take a crack at this since it relates to what I just worked on.

**Comment by ethanbb** [comment]
@jlangevin Sounds good! This should be a lot easier than when the test was first proposed now that we're putting snippet versions in the JS files.

**Comment by knod** [comment]
Great! I saw this originally and then couldn't track down where I saw it!

I was going to say that it may be possible to use something similar to the code in the google docs' scripts, but I now remember it's a complete hack because the g-docs can't treat the text like code. So nvm! Definitely feel free to run away with that!

Also @pporfilio is doing a lot of the heavy lifting with the snippets, so it may be worth coordinating with him on this localization stuff.

**Comment by jlangevin** [comment]
@knod and @pporfilio Here's the direction I started tinkering with based upon the current info on this thread.  But let me know if you have thoughts/concerns/other ideas.

Import localizations from src/localization/all.js and loop over each, comparing to EN.  This would ensure new localizations automatically get tested as they get added instead of pulling in specific localization files.

Use a recursive compare function which accepts two localization objects (and their names/keys for test output purposes).  Below would effectively walk down the tree of the EN localization object checking ES for the same structure/keys, but would not compare the underlying snippet text which is specific to the locale.

compare( key1, obj1, key2, obj2 ) {
 ...logic and tests here...

}
compare('EN', localizations['en'], 'ES', localizations['es']);

General function logic:

Test the two arguments for same type
  If so, check if we have an array/object
    if Array
      Test length
      if same length, loop over elements calling recursive function on each
   if Object
     Test Object.keys().sort() equal
     if same, loop over object properties calling recursive function on each
   Otherwise, its our localized text, so stop comparing/simply return true

**Comment by jlangevin** [comment]
This would be test/localization/all.test.js.  Test-wise, it would test:

1. localizations object exists
2. localizations has property 'EN'
3. localizations has one or more properties not 'EN'
4. compare each non-EN prop to EN using compare()
5. anything else folks think makes sense

**Comment by knod** [comment]
This sounds like some great brainstorming! And that's a very thorough all.test.js, too.

**Test logic:** Honestly, I'm the type of coder that has to go through implementation to see if logic works the way I want it to, but it sounds good from what I can see. A recursion pro ;) The only issue I see is with the arrays. The reason they're arrays is that sometimes the items in them have to be moved around. Maybe make a list of only objects, sort that, and loop through it? I'm not sure how sorting handles that, unfortunately. That may need to be a nested loop of its own that compares all objects in an array with all objects in the other array, though there are sometimes ways to make those iterations tend to be shorter.

**Results:** This is a little more tricky. Currently, our tests go through Travis CI and it doesn't accept a PR if it has warnings. Considering the person changing 'en.js' is unlikely to know all the other languages and be able to update them effectively before making a PR, I'm not sure what form our output should take. Plain old logs instead of warnings or errors? Writing a file that lists missing snippets and outdated snippets for each language? Some way for Travis to ignore those warnings? There must be a 'config' setting for that because it ignores lint output. Right now, we do have the google docs doing their crazy thing and that's informative, but it'd be nice to have something that's not a hack thoroughly checking the mismatches. @pporfilio , or anyone: Any thoughts on what would be useful output?

**Comment by jlangevin** [comment]
I totally agree on having to mess around with implementation logic.  I messed around quite bit before  suggesting anything.  Lol.  And while I believe this will work, I'm certainly open to other suggestions.

So with arrays, it would indeed compare each element in EN with it's corresponding element in the localization being tested.   So lets say EN has some array to which a third element 'c' is added (or 'c' existed and was moved up to the second position):

```
EN = {
  ...
  settings: [
    a: {...}
    c: {
      x: 'foo'
    },
    b: {...}
  ],
  ...
};
```

Then 'c' should be added to (or moved in) all other localizations with an appropriate placeholder.  I would think we'd want the test to fail until it was rectified since not having the same structure would be a breaking issue (once we can switch between localizations). The idea being that the only difference in localization files should be strings/primitives:

```
ES = {
  ...
  settings: [
    a: {...},
    c: {
      x: ''
    },
    b: {...}
  ],
  ...
};
```

So based upon your Results comments, we really have two things to test:  

1. same structure to avoid breaking the app
2. all strings having been translated.

My proposed solution solves 1 above, but that just avoids breaking the application.  I like your suggestion of logging.  We could compare strings and log when they're the same (non-translated) or empty string (placeholder). 

So for example, here's two pieces of EN and ES (I've altered to illustrate the issue).  Running the test from the console would log that the appName is the same and that toAboutPage is blank.  

```
EN = {
  ...
  homePage: {
    appName:          `Cliff Effects Tool`,
    prototypeNote:    `GUIDANCE PROTOTYPE*`,
    cautionaryNote:   `*This is a prototype and should not be used to make financial decisions`,
    toFirstInputPage: `Get Started`,
    toAboutPage:      `Learn More`,
  },
  ...
};
```

```
ES = {
  ...
  homePage: {
    appName:          `Cliff Effects Tool`,
    prototypeNote:    `GUIDANCE PROTOYPE*`,
    cautionaryNote:   `*Esto es una prototypa y no debe usarse para tomar decisiones financieras`,
    toFirstInputPage: `Empieza`,
    toAboutPage:      ``,
  }
  ...
};
```

Of course this doesn't 100% solve content issues.  Let's say someone incorrectly copies the wrong string from EN in to ES.  'Cliff Effects Tool' and 'Cliff Effects Too' would result in it thinking "hey, these are different so don't log anything."  But I guess that's what end user testing is for.  :)

**Comment by knod** [comment]
Hmm, we might take this to Slack. There are a few details that need some clarification in real-time.

**Comment by ethanbb** [comment]
So the thing with arrays in the snippets objects is that they are supposed to be allowed to have different orders and lengths in different languages. This is in order to allow flexibility in how the included objects and surrounding text flow together in a given language; the arrays indicate that "all these things should be rendered sequentially and be considered as one unit." So I don't think we want to recurse down to the level of individual array elements.

**Comment by jlangevin** [comment]
This has been addresses with the addition of the Localization Report in DevHud.  If changes are identified, new issues can be opened.
