### ISSUE TITLE
UI bug: graph titles in summary

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#546]
The graph titles in the summary page is center aligned.  This can bleed into the day/month/year toggles. Thinking of i18n, titles like Individual Benefit Amounts for Housing as Income Changes will be longer and should either be left aligned or have a set width and allow for multiple lines.

**Comment by knod** [comment]
I think this may be a issue about the site's size responsiveness, which hasn't been addressed yet. It's not currently in our scope, but if someone feels that that would be their main interest in contributing, it would be a great addition to the project.

**Comment by ethanbb** [comment]
Just want to add that the concern wasn't just about responsiveness, but also that the text may be longer when translated into other languages. That being said we haven't seen that be a problem yet, but it could be soon.

**Comment by knod** [comment]
Ah, got it. We could think about rethinking/restructuring those elements. It's a complex situation because we don't really control the chart stuff and the time buttons are basically an overlay on top of it. We'd need to re-design the look of it so that that was taken into account.

I'm concerned that there's so much to do right now that this might need to be put on the back-burner for the time being. If someone has a specific re-design in mind, that could help.

**Comment by knod** [comment]
We may be changing our chart lib, so we'll see what can happen with that.

**Comment by knod** [comment]
For now, we've done what work we can while keeping the time interval buttons. We've attempted to make adjustments for different screen sizes. Those measures will have to be re-done if layout changes because there doesn't seem to be a reasonable way to add buttons to the Highcharts element itself, but until some method for that becomes clear this is the best we can do.
