### ISSUE TITLE
consider text change "feedback"

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#549]
Thought feedback would provide a contact form; didn’t realize feedback was troubleshooting/help. Consider renaming.

**Comment by knod** [comment]
It's true, we haven't yet found a good name for it. Anyone have any ideas?

An alternative is to adjust how the form is presented - ask leading questions first about what kind of feedback they want to give - report a problem, give a suggestion, etc.

Just as a note, and sorry for bringing this up so much, depending on how blocking this problem is (i.e. would it stop someone from sending us feedback) this may or may not have a high priority at this point.

**Comment by knod** [comment]
We're trying out new text. I'm not sure whether or not it'll be more clear that it can be for both bug reports and general feedback so we'll have to see, but it's more in-line with plain language. We'll keep our eye out for something better.
