### ISSUE TITLE
Do users have a use case to download the data? Attach to a internal case file?

### ISSUE THREAD

**Issue by ohmegasquared** [codeforboston/cliff-effects#555]
Is this there a use case to save the data?

**Comment by knod** [comment]
Right now because of concerns about privacy and security, we haven't allowed people to download or save the data. Those issues are a bit out of our scope. That does remind me, though, that it could be useful to have a printable version of the data. I'm not sure if that would have security and privacy issues, though, or how we could do that without a file being saved to the computer.

**Comment by knod** [comment]
It must seem like I'm shooting down a lot of these thoughts. Sorry about that. The disadvantage of having a fresh perspective on the project is that you don't know the history and context of what we've done, so some of the things you observe has already been covered and, to be plain about it, get dismissed. In my opinion, though, the advantage of having a fresh perspective, greatly outweighs those unfortunate downsides - you've come up with a lot of great thoughts we either hadn't considered or had lost along the way.

Thanks for taking the risks inherent in giving us a booster shot with a new set of eyes.

**Comment by knod** [comment]
We've added the ability to print the text summary of the results. That'll be it for now till we figure out the data storing thing.
