### ISSUE TITLE
Allow deployment selectively to multiple locations

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#60]
open research Q.

**Comment by WillMcIntosh** [comment]
## Notes from what we found last night
* It looks like we can change the "deploy" script in package.json to run `node my-deploy-file.js`
    * We wanted "deploy" to get the user's github repo and deploy there
* We talked about creating a "deploy-production" script that deploys the way we're deploying now, to ghpages
* There is also a node package that may be useful called [exp-deploy](https://www.npmjs.com/package/exp-deploy) which handles different deployment tasks such as staging, production, test

**Comment by knod** [comment]
Preventing people from accidentally deploying to the production site is a good thought to start with. We may want to make a second issue (or adjust this issue) to cover being able to deploy to multiple sites. Either before or after the first prototype is done, we'll need a way to deploy to a live site and a way to deploy to a dev site, so it's going to have to be done one way or another.

What follows arose from a discussion between Will and myself. If we create a new issue, I'll move this comment to that issue.

So, my best guess at the different stages of complexity, from most 'simple' to more complex:
1. Require a confirmation before deploying. This assumes we're deploying to just one site.
2. (Maybe almost as 'simple' as 1) Ability to deploy to either live site or to dev site.
3. (A very short step from 2) Ability to deploy to live site, dev site, and your own gh-pages branch. If devs could deploy to their own gh-pages branch, they could easily show anyone whatever they're experimenting with. 
4. A way to customize where you're deploying to in general. This can be more or less complex depending on the kind of interaction you want to provide.

[Edit: after taking a closer think about what info we have and the complexity/simplicity of what we know, numbers 2-4 might be basically the same exact thing and be pretty darn simple to boot. Still don't know anything about 1. More research must be done.]

I think we might as well go for 2 or 3 because we've already found some solid leads on how to do those and haven't found ones for 1 yet. Here's a description of a behavior that can work for 2 (if you take off the last item) and 3 (if you keep the last item):
Assume `npm run` a the start of all of these:
- `deploy --dev` deploys to the dev site
- `deploy --live` deploys to the live site
- just plain `deploy` and/or `deploy --home` (or `--origin` or something) deploys to the gh-pages of the remote repo that this local repo calls 'origin'.

These might be useful:
https://docs.npmjs.com/cli/run-script
https://github.com/thlorenz/resolve-git-remote/blob/master/index.js
https://github.com/wilmoore/node-git-origin-url/blob/master/index.js

Using those examples, we can probably just have people deploy using the names of their remotes as commands, so a version of 4 is possibly just as easy as adding a remote. Hmmm...

**Comment by knod** [comment]
It looks like the current setup doesn't allow anyone to deploy to here from a fork, which is great! It's unclear yet whether it does allow people to deploy to their own fork, and it definitely doesn't allow deployment to multiple sites. That's not relevant to the current title 'Provide a check to ensure deploy doesn't accidentally deploy to production', but we have a lot of notes here relevant to possible future work, so I'm going to edit the title.

**Comment by knod** [comment]
@WillMcIntosh: Maybe links to a codepen?

**Comment by knod** [comment]
This is where we're currently putting our desire for the ability to deploy to a live and a dev site for when this goes to beta testers. I'm not sure that was ever made clear and definitely let me know if that's not what we want, but that was my understanding so that if something goes wrong while we dev, the testing site won't be affected.

**Comment by knod** [comment]
It seems that it's currently impossible to deploy to something that is not your origin. It's possible that ejecting from create-react-app would allow us to tinker with this, but it's not totally clear.

If we do have a deployment site and a live site, we'll have to do it manually, and maybe somewhat painfully. Because of how the settings work for this, the least painful, in some ways, would be to use a different account with a new repo called 'cliff-effects'. If we want, I can make an organization in which we can then create this repo.

**Comment by knod** [comment]
We'll revisit this if it seems needed.
