### ISSUE TITLE
Text summary of benefits changes

### ISSUE THREAD

**Issue by snyderc** [codeforboston/cliff-effects#687]
Separated this out from #554.

Goal: "More detailed information about the benefit changes written out in text as opposed to in a table or some other visual representation."

**Comment by knod** [comment]
That's a good start. I think it may need some tweaks. Based only on the scant judgement I've developed while working on this project, this is one possibility:

If your family's income changes from $X a month to $Y a month, your SNAP voucher will change from $X a month to $Y a month and your Section 8 voucher will change from $X a month to $Y a month. [Note: for some benefit programs, it may need to be a yearly amount.] That means that your total benefits will change from $X a month to $Y a month.

If it's all added together, your household will go from bringing in $X a month to $Y a month, which is $Z less/more than before.

[In future:]
Since you spend about $A a month right now, [is it possible for you to spend $B less/that will mean that you will have $B extra] each month[?/.]

**Comment by knod** [comment]
Also, the amounts in the table are rounded to the dollar. Should we change that? Should we put 'about' everywhere?

**Comment by ethanbb** [comment]
Could we not round the amounts to the dollar? After all, we talk about a "50 cent raise" in the intro- and I'm guessing that if you're using this tool, you probably care about amounts down to the cent (at least for weekly).

**Comment by knod** [comment]
Yeah, but this table in particular reports in monthly only. It was requested that monthly be used for this table, though we could probably do the same as other graphs and offer a time interval option with the default set to monthly...?

**Comment by ethanbb** [comment]
OK, I still think we can display cents even for monthly values. If not though, I guess for consistency we can just use the same rounded numbers in the text summary. I don't like the idea of saying "about" because it's vague - it makes you wonder, how uncertain are we?

**Comment by knod** [comment]
Yeah. Hmm. Maybe I'll ask Kristin how she thinks the clients might prefer it. I'd rather ask the clients, but I don't really have access to them :/

**Comment by knod** [comment]
Kristin says rounding is better for monthly amounts. I'll ask her if she wants something different for weekly amounts.

**Comment by knod** [comment]
Taken over by #763.
