### ISSUE TITLE
Bring version numbers from en google doc into en.js and update snippet names accordingly

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#752]

**Comment by knod** [comment]
This is great to finally have as an issue! And some PRs! Also, maybe press pause for a sec!

To put it in a place where others can find it, I'm repeating what I said in #755:
@jlangevin and I just started talking about ways to dynamically strip out version numbers when the objects are created so that we don't have to constantly change these. There are some drawbacks - mainly that, in its current incarnation in my head, it would be invisible to anyone unfamiliar with the code base.

Sorry for the roller coaster ride. I think it may still be worth pulling in those PRs since they're something that's actually done while this thing is just an idea.

**Comment by knod** [comment]
I think everything has version numbers now!
