### ISSUE TITLE
Add a warning and user interaction to ensure that users understand this tool is a prototype

### ISSUE THREAD

**Issue by pporfilio** [codeforboston/cliff-effects#761]
It's important that someone not think that the data the cliff effects tool provides is 100% accurate while it's still a prototype. In user testing, we've found that people do trust the results from the tool and do not understand that it's a prototype.

One idea is to present a warning that states that the tool is a prototype and should not be used to make financial decisions, and require the user to click one of two buttons indicating that they understand the warning.

https://docs.google.com/document/d/1Np8AvGmkKA7g6fSc51CauY-aj4SZ_E286MrJNK9qqa0/edit#

**Comment by knod** [comment]
One option is to have a red modal open that offers two choices (radio buttons). One says, 'I can count on what this tool tells me' and the other says 'I **can't** count on what this tool tells me'. Until they've selected the right one, the 'Next' button won't be enabled.

**Comment by jlangevin** [comment]
I'm not liking the idea of having a radio button that basically does nothing.  Usually sites will have something like two buttons - accept/okay allows them to continue and decline/no redirects them somewhere else.  

Alternatively, a checkbox is used with a label like [ ] I understand... and checking the box triggers display of a Continue button which closes the dialog.

**Comment by knod** [comment]
Hmm, I understand the convention, but I think this is a case where I'd prefer to break the convention in order to get people to actually pause and pay attention. I don't want people thinking, 'Ok, this is the usual thing where this app uselessly asks for my permission to share my data or whatever' because that's not at all what this is. We want the user to understand a completely different thing. Does that make sense?

In my mind, this isn't a consent form, it's a dialogue. I don't want them to be giving permission to share data, I want them to actually read the text that says they cannot trust the calculations.

**Comment by jlangevin** [comment]
Okay I've drastically simplified what the modal says and switched to radios as you've suggested.  However, it still bothers me that they affirm a negative statement "I can't trust..." to proceed.  So I used a positive "I understand that..."  We could change the instructions at the top to something like "Please indicate below that you understand..."

**Comment by knod** [comment]
I'll try to ping you for a real-time convo to discuss the details. Maybe I have the wrong end of the stick. It might be worth a group discussion.

**Comment by knod** [comment]
What I meant to say is that I wanted to check in and see if we were having a difference of a opinion that I feel everyone has a right to express. I just find those easier in real-time.

**Comment by knod** [comment]
Closed by #831
