### ISSUE TITLE
Abstract benefit calculations so all chart things are getting them the same way

### ISSUE THREAD

**Issue by knod** [codeforboston/cliff-effects#784]

**Comment by ethanbb** [comment]
When looking through PR #785, I had some misgivings about the way we're reusing the `future` client object for each hypothetical income when constructing the stacked area or line graph. I'll summarize what @knod and I were talking about here.

We recently realized that we had a bug in our calculation of SNAP benefits when Section 8 benefits also applied. (@knod correct me if I get the details wrong here.) The issue was that the Section 8 benefit change would change the client's housing expenses, which in turn affects the SNAP calculation. So we had to make sure to modify the `future` `rentShare` value after calculating Section 8, and then use that new value when calculating SNAP.

This made us think a little about how things could look if we eventually added a larger number of benefit programs, each of which could affect different pieces of the `future` client situation. The `applyAndPushBenefits` function introduced in #785 provides a systematic way for each benefit calculation to also mutate `future` after returning its result to reflect the updated situation. This works if we always calculate benefits in a canonical order (such that changes always precede the calculation of benefits that depend on them) and only read from `future` rather than `current` within each calculation.

My issue was with reusing `future` for each of several hypothetical incomes (the values on the x-axis) rather than resetting it to `current` each time. My concern is that, if benefit A is to be calculated before benefit B, while we may know that A does not need to know about the value of B or any side-effects of B, that does not necessarily imply that A does not depend on the value of something that B touches _before_ B modifies it. 

But that probably should be the case, and maybe I'm off-base about this. I was thinking that B could modify something general in `future` whose old value might have been relevant to A, and this could mess up the A calculation on the next iteration (when the modified value is still present in `future`). However, it should probably be the case that anything B touches is not relevant to and not even read by A (or anything else that comes before B), so it won't matter that the change is carried over. That wasn't obvious to me until just now, so maybe we should either express that clearly somewhere (on the wiki?) or somehow work that requirement into the code (without over-engineering it, hopefully).

Sorry for rambling on! I'm interested to hear other people's thoughts!

**Comment by knod** [comment]
Closed by #785 unless someone else has some more notes. If I'm not mistaken, folks discussing this seemed to have come to the conclusion that the last paragraph is correct. Not sure how to express this clearly yet, so not sure what to put on the wiki :/

**Comment by knod** [comment]
Still worth thinking about. Should we make a new issue? One including the idea to make some requirements in the code? It seems to me that any requirements that would be in the code would make things less maintainable, but maybe we can figure something out.
