### ISSUE TITLE
DEL: Non-functional UI elements from production

### ISSUE THREAD

**Issue by lianilychee** [codeforboston/cliff-effects#9]
Remove:
* [x] Save results
* [x] Existing clients section
* [x] Login button
* [x] Alert that occurs after one submits a new client's info

Rationale:  Current version shows potential functionality.  Moving to production, therefore removing non-functional elements.

**Comment by nlkassad** [comment]
*[ ] @lianilychee test check boxes

**Comment by knod** [comment]
Are you saying that you'd prefer that the demo go straight to filling out the form instead of going through the other steps first?

**Comment by knod** [comment]
I made a pull request to the dev branch with a completely simplified (just the form) version a few days ago. Pinged you folks for a review of it, but I think you haven't had a chance to review it.

Also, there seemed to still be some discussion going on as to whether to go with such a simplified version or not.

**Comment by carpeliam** [comment]
I saw a comment in slack from Alec (@danaher2):
> the search function is working, albeit with fake client data. My 2 cents is that I think we should only remove functionality that is truly not functional such as the login and creating a new client account. I think getting feedback on what has been built so far, including selecting a client and adding a visit is worthwhile.

I think we should remove the search functionality for now, because we can't save clients, and so the search functionality can't search real clients. I'd like to differentiate between a **high fidelity mockup**, which should be used in client interviews to get feedback on _potential_ direction, and a **minimum viable product**, which should be include only features that provide current value.

While we want to include features like search in something like a high fidelity mockup, we should keep it out of our production release until case workers can use it to make their jobs easier.

**Comment by knod** [comment]
(Taking it as a given that not all forms/questions/calculations have been implemented yet)

@carpeliam or any folks: Have you had a chance to clone and try the simplified version (https://github.com/knod/cliff-effects-1/tree/simple for a direct link)? If so, is it what you think the flow of the project is looking for right now? It's simplified down to just the form, but the goal is currently everything except the listed items, I can try to do a version like that too.

**Comment by knod** [comment]
Starting work on item 1.

**Comment by knod** [comment]
Starting work on item 2

**Comment by knod** [comment]
Starting work on item 3

**Comment by knod** [comment]
Starting work on item 4

**Comment by knod** [comment]
The changes should now be deployed. Just to confirm, you don't want any of the other non-functioning elements removed?

**Comment by lianilychee** [comment]
@knod yup, that's right!
